import { Colors } from './theme';
import type { ClothingItem, Outfit } from './types';

// Sample items ship without a photo — the closet renders a generated
// swatch (tint + category icon) for any item that has no imageUri, which is
// also what a freshly-added item looks like before its first photo.
export const SAMPLE_CLOTHING_ITEMS: ClothingItem[] = [
  {
    id: 'top-1',
    name: 'Silk Camisole',
    category: 'tops',
    swatchColor: Colors.beige,
    color: 'Ivory',
    seasons: ['spring', 'summer'],
    brand: 'Maison Rive',
    style: 'Minimalist',
    createdAt: daysAgo(40),
  },
  {
    id: 'top-2',
    name: 'Merino Turtleneck',
    category: 'tops',
    swatchColor: Colors.mushroom,
    color: 'Charcoal',
    seasons: ['fall', 'winter'],
    brand: 'Sable & Co.',
    style: 'Tailored',
    createdAt: daysAgo(12),
  },
  {
    id: 'top-3',
    name: 'Cotton Poplin Shirt',
    category: 'tops',
    swatchColor: Colors.beige,
    color: 'Stone',
    seasons: ['spring', 'fall'],
    brand: 'Ferro & Ames',
    style: 'Classic',
    createdAt: daysAgo(65),
  },
  {
    id: 'top-4',
    name: 'Cashmere Crewneck',
    category: 'tops',
    swatchColor: Colors.mushroom,
    color: 'Taupe',
    seasons: ['fall', 'winter'],
    brand: 'Sable & Co.',
    style: 'Cozy',
    createdAt: daysAgo(5),
  },
  {
    id: 'bottom-1',
    name: 'Tailored Wide-Leg Trouser',
    category: 'bottoms',
    swatchColor: Colors.mushroom,
    color: 'Espresso',
    seasons: ['fall', 'winter'],
    brand: 'Ferro & Ames',
    style: 'Tailored',
    createdAt: daysAgo(80),
  },
  {
    id: 'bottom-2',
    name: 'Straight-Leg Denim',
    category: 'bottoms',
    swatchColor: Colors.beige,
    color: 'Washed Indigo',
    seasons: ['spring', 'fall'],
    brand: 'Atelier Denim',
    style: 'Classic',
    createdAt: daysAgo(22),
  },
  {
    id: 'bottom-3',
    name: 'Pleated Midi Skirt',
    category: 'bottoms',
    swatchColor: Colors.mushroom,
    color: 'Stone',
    seasons: ['spring', 'summer'],
    brand: 'Maison Rive',
    style: 'Elegant',
    createdAt: daysAgo(3),
  },
  {
    id: 'bottom-4',
    name: 'Linen Trouser',
    category: 'bottoms',
    swatchColor: Colors.beige,
    color: 'Mushroom',
    seasons: ['summer'],
    brand: 'Sable & Co.',
    style: 'Relaxed',
    createdAt: daysAgo(50),
  },
  {
    id: 'dress-1',
    name: 'Silk Slip Dress',
    category: 'dresses',
    swatchColor: Colors.beige,
    color: 'Champagne',
    seasons: ['summer'],
    brand: 'Maison Rive',
    style: 'Elegant',
    createdAt: daysAgo(18),
  },
  {
    id: 'dress-2',
    name: 'Wool Wrap Dress',
    category: 'dresses',
    swatchColor: Colors.mushroom,
    color: 'Espresso',
    seasons: ['fall', 'winter'],
    brand: 'Sable & Co.',
    style: 'Tailored',
    createdAt: daysAgo(9),
  },
  {
    id: 'dress-3',
    name: 'Linen Shirt Dress',
    category: 'dresses',
    swatchColor: Colors.beige,
    color: 'Stone',
    seasons: ['spring', 'summer'],
    brand: 'Ferro & Ames',
    style: 'Minimalist',
    createdAt: daysAgo(30),
  },
  {
    id: 'shoe-1',
    name: 'Leather Loafers',
    category: 'shoes',
    swatchColor: Colors.mushroom,
    color: 'Espresso',
    seasons: ['spring', 'fall', 'winter'],
    brand: 'Corso',
    style: 'Classic',
    createdAt: daysAgo(60),
  },
  {
    id: 'shoe-2',
    name: 'Suede Ankle Boots',
    category: 'shoes',
    swatchColor: Colors.mushroom,
    color: 'Taupe',
    seasons: ['fall', 'winter'],
    brand: 'Corso',
    style: 'Tailored',
    createdAt: daysAgo(14),
  },
  {
    id: 'shoe-3',
    name: 'Ballet Flats',
    category: 'shoes',
    swatchColor: Colors.beige,
    color: 'Ivory',
    seasons: ['spring', 'summer'],
    brand: 'Maison Rive',
    style: 'Minimalist',
    createdAt: daysAgo(7),
  },
  {
    id: 'jacket-1',
    name: 'Wool Overcoat',
    category: 'jackets',
    swatchColor: Colors.beige,
    color: 'Camel',
    seasons: ['winter'],
    brand: 'Ferro & Ames',
    style: 'Tailored',
    createdAt: daysAgo(20),
  },
  {
    id: 'jacket-2',
    name: 'Tailored Blazer',
    category: 'jackets',
    swatchColor: Colors.mushroom,
    color: 'Charcoal',
    seasons: ['spring', 'fall'],
    brand: 'Sable & Co.',
    style: 'Classic',
    createdAt: daysAgo(45),
  },
  {
    id: 'bag-1',
    name: 'Structured Leather Tote',
    category: 'bags',
    swatchColor: Colors.mushroom,
    color: 'Espresso',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    brand: 'Corso',
    style: 'Minimalist',
    createdAt: daysAgo(35),
  },
  {
    id: 'bag-2',
    name: 'Suede Crossbody',
    category: 'bags',
    swatchColor: Colors.beige,
    color: 'Taupe',
    seasons: ['spring', 'summer'],
    brand: 'Corso',
    style: 'Relaxed',
    createdAt: daysAgo(4),
  },
  {
    id: 'jewelry-1',
    name: 'Gold Chain Necklace',
    category: 'jewelry',
    swatchColor: Colors.beige,
    color: 'Gold',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    brand: 'Atelier Vie',
    style: 'Delicate',
    createdAt: daysAgo(55),
  },
  {
    id: 'jewelry-2',
    name: 'Pearl Drop Earrings',
    category: 'jewelry',
    swatchColor: Colors.mushroom,
    color: 'Pearl',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    brand: 'Atelier Vie',
    style: 'Classic',
    createdAt: daysAgo(2),
  },
  {
    id: 'hat-1',
    name: 'Wool Fedora',
    category: 'hats',
    swatchColor: Colors.mushroom,
    color: 'Charcoal',
    seasons: ['fall', 'winter'],
    brand: 'Ferro & Ames',
    style: 'Tailored',
    createdAt: daysAgo(28),
  },
  {
    id: 'belt-1',
    name: 'Leather Waist Belt',
    category: 'belts',
    swatchColor: Colors.beige,
    color: 'Espresso',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    brand: 'Corso',
    style: 'Classic',
    createdAt: daysAgo(16),
  },
  {
    id: 'accessory-1',
    name: 'Silk Scarf',
    category: 'accessories',
    swatchColor: Colors.mushroom,
    color: 'Stone',
    seasons: ['fall', 'spring'],
    brand: 'Maison Rive',
    style: 'Elegant',
    createdAt: daysAgo(6),
  },
];

export const SAMPLE_OUTFITS: Outfit[] = [
  {
    id: 'outfit-1',
    name: 'Weekend Errands',
    mode: 'top-bottom',
    slots: [
      { category: 'tops', itemId: 'top-1' },
      { category: 'bottoms', itemId: 'bottom-2' },
      { category: 'shoes', itemId: 'shoe-3' },
      { category: 'bags', itemId: 'bag-2' },
    ],
    occasion: 'casual',
    season: 'spring',
    mood: 'Relaxed',
    notes: 'An easy, considered fit for running errands.',
    favorite: true,
    createdAt: daysAgo(25),
    lastWornAt: daysAgo(3),
    wearCount: 4,
  },
  {
    id: 'outfit-2',
    name: 'Evening Dinner',
    mode: 'full-body',
    slots: [
      { category: 'dresses', itemId: 'dress-2' },
      { category: 'shoes', itemId: 'shoe-2' },
      { category: 'bags', itemId: 'bag-1' },
      { category: 'jewelry', itemId: 'jewelry-1' },
    ],
    occasion: 'date-night',
    season: 'winter',
    mood: 'Elegant',
    notes: 'Wool and leather, kept quiet and refined.',
    favorite: true,
    createdAt: daysAgo(10),
    lastWornAt: daysAgo(10),
    wearCount: 1,
  },
  {
    id: 'outfit-3',
    name: 'Studio to Street',
    mode: 'top-bottom',
    slots: [
      { category: 'tops', itemId: 'top-4' },
      { category: 'bottoms', itemId: 'bottom-4' },
      { category: 'shoes', itemId: 'shoe-1' },
      { category: 'jewelry', itemId: 'jewelry-2' },
    ],
    occasion: 'work',
    season: 'fall',
    mood: 'Composed',
    notes: '',
    favorite: false,
    createdAt: daysAgo(1),
    lastWornAt: null,
    wearCount: 0,
  },
];

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
